receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318

exporters:
  otlphttp/flaggo:
    logs_endpoint: http://localhost:5090/v1/logs

service:
  pipelines:
    logs:
      receivers: [otlp]
      exporters: [otlphttp/flaggo]
