<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.4" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <ProjectReference Include="..\..\modules\contract\src\Flaggo.Contract\Flaggo.Contract.csproj" />
    <ProjectReference Include="..\..\modules\contract-store\src\Flaggo.ContractStore\Flaggo.ContractStore.csproj" />
    <ProjectReference Include="..\..\modules\decision\src\Flaggo.Decision\Flaggo.Decision.csproj" />
    <ProjectReference Include="..\..\modules\executable-store\src\Flaggo.ExecutableStore\Flaggo.ExecutableStore.csproj" />
    <ProjectReference Include="..\..\modules\expression\src\Flaggo.Expressions\Flaggo.Expressions.csproj" />
    <ProjectReference Include="..\..\modules\hosting\src\Flaggo.ServiceHosting\Flaggo.ServiceHosting.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="..\..\contracts\fixtures\management\decision-contract\01-validate-valid.json"
             Link="Fixtures\validate-contract-valid.json"
             CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>