<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <ProjectReference Include="..\..\..\..\packages\shared-contracts\src\Flaggo.Shared.Contracts\Flaggo.Shared.Contracts.csproj" />
    <ProjectReference Include="..\..\..\..\modules\registry\src\Flaggo.Registry\Flaggo.Registry.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="..\..\..\..\contracts\fixtures\management\definition-bundle\04-apply-approved-receipt.json"
                      LogicalName="Flaggo.Hosting.ApprovedLocalManifest.json" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
